config/routes.rb
Rails.application.routes.draw do
  resources :trade_items
  resources :trades
  get 'search', to: 'search#index', as: 'search_index'
  get 'search/:query', to: 'search#search', as: 'search_query'

  get 'home/index'

  get 'sessions/new', to: 'sessions#new', as: 'new_session'
  post 'sessions/create', to: 'sessions#create', as: 'create_session'
  delete 'sessions/destroy', to: 'sessions#destroy', as: 'destroy_session'

  post 'trades/:id/confirm', to: 'trades#confirm_trade', as: 'confirm_trade'

  resources :users do
    resources :mangas, shallow: true
    resources :trades, shallow: true
  end

  root 'home#index'
end

app/models/manga.rb
class Manga < ApplicationRecord
  validates :title, :user, presence: true
  validate :image_exists?
  belongs_to :user

  def image_exists?
    unless File.exists?("app/assets/images/" + image_url) and not image_url.nil?
      errors.add(:image_url, "could not be found!")
    end
  end
end

app/controllers/mangas_controller.rb
class MangasController < ApplicationController
  before_action :set_manga, only: %i[ show edit update destroy ]

  # GET /mangas or /mangas.json
  def index
    @mangas = Manga.where(user_id: session[:user_id])
  end

  # GET /mangas/1 or /mangas/1.json
  def show
  end

  # GET /mangas/new
  def new
    @manga = Manga.new
  end

  # GET /mangas/1/edit
  def edit
  end

  # POST /mangas or /mangas.json
  def create
    @manga = Manga.new(manga_params)
    @user = User.find(@manga.user_id)

    respond_to do |format|
      if @manga.save
        format.html { redirect_to @user, notice: "Manga was successfully created." }
        format.json { render :show, status: :created, location: @manga }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @manga.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mangas/1 or /mangas/1.json
  def update
    respond_to do |format|
      if @manga.update(manga_params)
        format.html { redirect_to user_url(@user), notice: "Manga was successfully updated." }
        format.json { render :show, status: :ok, location: @manga }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @manga.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mangas/1 or /mangas/1.json
  def destroy
    @manga.destroy
    flash[:notice] = "Manga was successfully destroyed"

    respond_to do |format|
      format.html { redirect_to user_mangas_url(@user) } # TODO: Couldn't redirect properly
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manga
      @manga = Manga.find(params[:id])
    end


    # Only allow a list of trusted parameters through.
    def manga_params
      params.require(:manga).permit(:title, :genre, :description, :volumes, :user_id, :image_url)
    end
end

app/helpers/mangas_helper.rb
module MangasHelper
end

app/views/mangas/_edit_form.html.erb
<%= form_with(model: manga) do |form| %>
  <% if manga.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(manga.errors.count, "error") %> prohibited this manga from being saved:</h2>

      <ul>
        <% manga.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :genre, style: "display: block" %>
    <%= form.text_field :genre %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :volumes, style: "display: block" %>
    <%= form.text_field :volumes %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :image_url, style: "display: block" %>
    <%= form.text_field :image_url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/mangas/_form.html.erb
<%= form_with(model: manga) do |form| %>
  <% if manga.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(manga.errors.count, "error") %> prohibited this manga from being saved:</h2>

      <ul>
        <% manga.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :genre, style: "display: block" %>
    <%= form.text_field :genre %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :volumes, style: "display: block" %>
    <%= form.text_field :volumes %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :image_url, style: "display: block" %>
    <%= form.text_field :image_url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/mangas/_manga.html.erb
<div id="<%= dom_id manga %>">
  <div class="card m-2" style="width: 18rem;">
    <%= image_tag manga.image_url, class: "card-img-top" %>
    <div class="card-body">
      <h5 class="card-title"><%= manga.title %></h5>
      <h6 class="card-title text-muted"><%= manga.genre %></h6>
      <p class="card-text"><%= manga.description %></div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">Elindeki ciltler: <%= manga.volumes %></li>
    </ul>
    <div class="card-body">
      <%= link_to "Mangayı sil", manga_path(manga), data: { turbo_method: :delete }, class: "card-link" %>
      <%= link_to "Mangayı düzenle", edit_manga_path(manga), class: "card-link" %>
    </div>
    <div class="card-footer text-muted">
      <%= manga.created_at %> tarihinde ekledin
    </div>
  </div>
</div>

app/views/mangas/edit.html.erb
<h1>Editing manga</h1>

<%= render "edit_form", manga: @manga %>

<br>

<div>
  <%= link_to "Show this manga", @manga %> |
  <%= link_to "Back to mangas", user_mangas_path(@user) %>
</div>

app/views/mangas/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Mangas</h1>

<div id="mangas">
  <% @mangas.each do |manga| %>
    <%= render manga %>
    <p>
      <%= link_to "Show this manga", manga %>
    </p>
  <% end %>
</div>

<%= link_to "New manga", new_user_manga_path %>

app/views/mangas/new.html.erb
<h1>New manga</h1>

<%= render "form", manga: @manga %>

<br>

<div>
  <%= link_to "Back to mangas", user_path(@user) %>
</div>

app/views/mangas/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @manga %>

<div>
  <%= link_to "Edit this manga", edit_manga_path(@manga) %> |
  <%= link_to "Back to mangas", user_path(@user) %>

  <%= button_to "Destroy this manga", @manga, method: :delete %>
</div>