config/routes.rb
Rails.application.routes.draw do
  resources :trade_items
  resources :trades
  get 'search', to: 'search#index', as: 'search_index'
  get 'search/:query', to: 'search#search', as: 'search_query'

  get 'home/index'

  get 'sessions/new', to: 'sessions#new', as: 'new_session'
  post 'sessions/create', to: 'sessions#create', as: 'create_session'
  delete 'sessions/destroy', to: 'sessions#destroy', as: 'destroy_session'

  post 'trades/:id/confirm', to: 'trades#confirm_trade', as: 'confirm_trade'

  resources :users do
    resources :mangas, shallow: true
    resources :trades, shallow: true
  end

  root 'home#index'
end

app/models/trade_item.rb
class TradeItem < ApplicationRecord
  belongs_to :trade
  belongs_to :manga
end

app/controllers/trade_item_controller.rb
class TradeItemController < ApplicationController
end

app/controllers/trade_items_controller.rb
class TradeItemsController < ApplicationController
  skip_before_action :authorize, only: %i[ create ]
  before_action :set_trade_item, only: %i[ show edit update destroy ]

  # GET /trade_items or /trade_items.json
  def index
    @trade_items = TradeItem.all
  end

  # GET /trade_items/1 or /trade_items/1.json
  def show
  end

  # GET /trade_items/new
  def new
    @trade_item = TradeItem.new
  end

  # GET /trade_items/1/edit
  def edit
  end

  # POST /trade_items or /trade_items.json
  def create
    @trade_item = TradeItem.new(trade_item_params)
    @trade = Trade.find(@trade_item.trade_id)

    respond_to do |format|
      if @trade_item.save
        format.html { redirect_to trade_url(@trade), notice: "Trade item was successfully created." }
        format.json { render :show, status: :created, location: @trade_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @trade_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trade_items/1 or /trade_items/1.json
  def update
    respond_to do |format|
      if @trade_item.update(trade_item_params)
        format.html { redirect_to trade_item_url(@trade_item), notice: "Trade item was successfully updated." }
        format.json { render :show, status: :ok, location: @trade_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @trade_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trade_items/1 or /trade_items/1.json
  def destroy
    @trade_item.destroy

    respond_to do |format|
      format.html { redirect_to trade_url, notice: "Trade item was successfully removed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trade_item
      @trade_item = TradeItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def trade_item_params
      params.require(:trade_item).permit(:trade_id, :manga_id)
    end
end

app/helpers/trade_item_helper.rb
module TradeItemHelper
end

app/helpers/trade_items_helper.rb
module TradeItemsHelper
end

app/views/trade_items/_form.html.erb
<%= form_with(model: trade_item) do |form| %>
  <% if trade_item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(trade_item.errors.count, "error") %> prohibited this trade_item from being saved:</h2>

      <ul>
        <% trade_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :trade_id, style: "display: block" %>
    <%= form.text_field :trade_id %>
  </div>

  <div>
    <%= form.label :manga_id, style: "display: block" %>
    <%= form.text_field :manga_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/trade_items/_trade_item.html.erb
<div id="<%= dom_id trade_item %>">
  <li>
    <%= Manga.find(trade_item.manga_id).title %>
    <%= button_to "Remove", trade_item_path(trade_item), method: :delete %>
  </li>
</div>

app/views/trade_items/edit.html.erb
<h1>Editing trade item</h1>

<%= render "form", trade_item: @trade_item %>

<br>

<div>
  <%= link_to "Show this trade item", @trade_item %> |
  <%= link_to "Back to trade items", trade_items_path %>
</div>

app/views/trade_items/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Trade items</h1>

<div id="trade_items">
  <% @trade_items.each do |trade_item| %>
    <%= render trade_item %>
    <p>
      <%= link_to "Show this trade item", trade_item %>
    </p>
  <% end %>
</div>

<%= link_to "New trade item", new_trade_item_path %>

app/views/trade_items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @trade_item %>

<div>
  <%= link_to "Edit this trade item", edit_trade_item_path(@trade_item) %> |
  <%= link_to "Back to trade items", trade_items_path %>

  <%= button_to "Destroy this trade item", @trade_item, method: :delete %>
</div>