config/routes.rb
Rails.application.routes.draw do
  resources :trade_items
  resources :trades
  get 'search', to: 'search#index', as: 'search_index'
  get 'search/:query', to: 'search#search', as: 'search_query'

  get 'home/index'

  get 'sessions/new', to: 'sessions#new', as: 'new_session'
  post 'sessions/create', to: 'sessions#create', as: 'create_session'
  delete 'sessions/destroy', to: 'sessions#destroy', as: 'destroy_session'

  post 'trades/:id/confirm', to: 'trades#confirm_trade', as: 'confirm_trade'

  resources :users do
    resources :mangas, shallow: true
    resources :trades, shallow: true
  end

  root 'home#index'
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, :email, presence: true
  has_secure_password

  has_many :mangas, dependent: :destroy

  has_many :sent_trades, class_name: 'Trade', foreign_key: :sender_id
  has_many :recieved_trades, class_name: 'Trade', foreign_key: :recipient_id
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorize, only: %i[new create]
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    @mangas = Manga.where(user_id: @user.id)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to new_session_url, notice: 'Başarıyla kayıt oldunuz, şimdi giriş yapabilirsiniz!' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :email, class: "form-label" %>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :decription, class: "form-label" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :password %>
    <%= form.password_field :password, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: "form-control" %>
  </div>

  <div class="d-grid">
    <%= form.submit "Kayıt Ol", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<p class="user-text">Kullanıcı Adı: <%= user.name %></p>
<p class="user-text">Elektronik Posta: <%= user.email %></p>
<p class="user-description"><%= user.description %></p>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %> |
  <%= link_to "Show trades", trades_path %>


  <%= button_to "Destroy this user", @user, method: :delete %>
</div>
<hr/>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<%= image_tag "alchemist.jpg", size: "240x148", class: "sign-up-image rounded mx-auto m-3" %>

<h1 class="text-center">Kayıt Ol</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Anasayfaya dön", root_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>



<%= render @user %>





<div class="d-flex flex-column align-items-center">
  <h4 class="m-1">Mangalarım</h4>
  <% if @user.id == session[:user_id] %>
    <%= button_to "+ Ekle", new_user_manga_path(@user), class: "btn btn-success btn-sm m-1", method: :get %>
  <% else %>
    <%= button_to "Takas yap", new_trade_path, class: "btn btn-success btn-sm m-1", method: :get, params: { recipient_id: @user.id} %>
  <% end %>
  <%= render @mangas %>
</div>