config/routes.rb
Rails.application.routes.draw do
  resources :trade_items
  resources :trades
  get 'search', to: 'search#index', as: 'search_index'
  get 'search/:query', to: 'search#search', as: 'search_query'

  get 'home/index'

  get 'sessions/new', to: 'sessions#new', as: 'new_session'
  post 'sessions/create', to: 'sessions#create', as: 'create_session'
  delete 'sessions/destroy', to: 'sessions#destroy', as: 'destroy_session'

  post 'trades/:id/confirm', to: 'trades#confirm_trade', as: 'confirm_trade'

  resources :users do
    resources :mangas, shallow: true
    resources :trades, shallow: true
  end

  root 'home#index'
end

app/models/trade.rb
class Trade < ApplicationRecord
  has_many :trade_items, dependent: :destroy

  belongs_to :sender, class_name: 'User'
  belongs_to :recipient, class_name: 'User'
end

app/controllers/trades_controller.rb
class TradesController < ApplicationController
  skip_before_action :authorize, only: %i[ confirm_trade ]

  before_action :set_trade, only: %i[ show edit update destroy confirm_trade ]
  before_action :set_user, only: %i[ new confirm_trade ]
  # GET /trades or /trades.json
  def index
    @trades = Trade.all
  end

  # GET /trades/1 or /trades/1.json
  def show
    @sender = User.find(@trade.sender_id)
    @recipient = User.find(@trade.recipient_id)
    @trade_items = @trade.trade_items
  end

  # GET /trades/new
  def new
    @trade = Trade.find_or_create_by(sender_id: @user.id, recipient_id: params[:recipient_id])
    respond_to do |format|
      format.html { redirect_to trade_path(@trade), notice: "Trade was successfully completed." }
    end
  end

  # GET /trades/1/edit
  def edit
  end

  def confirm_trade
    @trade.trade_items.each do |item|
      manga = Manga.find(item.manga_id)
      if manga.user_id == @trade.sender_id
        manga.update(user_id: @trade.recipient_id)
      else
        manga.update(user_id: @trade.sender_id)
      end
    end

    @trade.destroy
    respond_to do |format|
      format.html { redirect_to user_url(@user), notice: "Trade was successfully completed." }
    end
  end

  # POST /trades or /trades.json
  def create
    @trade = Trade.new(trade_params)

    respond_to do |format|
      if @trade.save
        format.html { redirect_to trade_url(@trade), notice: "Trade was successfully created." }
        format.json { render :show, status: :created, location: @trade }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @trade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trades/1 or /trades/1.json
  def update
    respond_to do |format|
      if @trade.update(trade_params)
        format.html { redirect_to trade_url(@trade), notice: "Trade was successfully updated." }
        format.json { render :show, status: :ok, location: @trade }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @trade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trades/1 or /trades/1.json
  def destroy
    @trade.destroy

    respond_to do |format|
      format.html { redirect_to trades_url, notice: "Trade was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_trade
    @trade = Trade.find(params[:id])
  end

  def set_user
    @user = User.find(session[:user_id])
  end

  # Only allow a list of trusted parameters through.
  def trade_params
    params.require(:trade).permit(:sender_id, :recipient_id)
  end
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/views/trades/_form.html.erb
<%= form_with(model: trade) do |form| %>
  <% if trade.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(trade.errors.count, "error") %> prohibited this trade from being saved:</h2>

      <ul>
        <% trade.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :sender_id, style: "display: block" %>
    <%= form.text_field :sender_id %>
  </div>

  <div>
    <%= form.label :recipient_id, style: "display: block" %>
    <%= form.text_field :recipient_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/trades/_manga_trade.html.erb
<li>
  <%= manga.title %>
  <% if not trade_mangas.include?(manga) %>
    <%= button_to "Add", trade_items_path, params: { trade_item: { trade_id: @trade.id, manga_id: manga.id } }, method: :post %>
  <% end %>
</li>

app/views/trades/_trade.html.erb
<div id="<%= dom_id trade %>">
  <p>
    <strong>Sender:</strong>
    <%= trade.sender_id %>
  </p>

  <p>
    <strong>Recipient:</strong>
    <%= trade.recipient_id %>
  </p>

</div>

app/views/trades/edit.html.erb
<h1>Editing trade</h1>

<%= render "form", trade: @trade %>

<br>

<div>
  <%= link_to "Show this trade", @trade %> |
  <%= link_to "Back to trades", trades_path %>
</div>

app/views/trades/index.html.erb
<p style="color: green"><%= notice %></p>



<% if @trades.empty? %>
  <h5>You don't have any trade requests!</h5>
<% else %>
  <div id="trades">
    <% @trades.each do |trade| %>
      <%= render trade %>
      <p>
        <%= link_to "Show this trade", trade %>
      </p>
    <% end %>
  </div>
<% end %>

app/views/trades/new.html.erb
<h1>New trade</h1>

<p>Selected items:</p>
<ul>
  <%= render @trade.trade_items %>
</ul>


<p>Sender: <%= @user.id %></p>
<ul>
  <% @user.mangas.each do |manga| %>
    <%= render "trades/manga_trade", manga: manga %>
  <% end %>
</ul>


<p>Recipient: <%= @recipient.id %></p>
<ul>
  <% @recipient.mangas.each do |manga| %>
    <%= render "trades/manga_trade", manga: manga %>
  <% end %>
</ul>
<div>
  <%= link_to "Back to trades", trades_path %>
</div>

app/views/trades/show.html.erb
<p style="color: green"><%= notice %></p>

<p>Selected items:</p>
<ul>
  <%= render @trade.trade_items %>
</ul>


<p>Sender: <%= @user.id %></p>
<ul>
  <% @user.mangas.each do |manga| %>
    <%= render "trades/manga_trade", manga: manga, trade_mangas: @trade.trade_items.map { |item| item.manga } %>
  <% end %>
</ul>


<p>Recipient: <%= @recipient.id %></p>
<ul>
  <% @recipient.mangas.each do |manga| %>
    <%= render "trades/manga_trade", manga: manga, trade_mangas: @trade.trade_items.map { |item| item.manga } %>
  <% end %>
</ul>

<div>
  <div class="btn-group">
    <%= button_to "Destroy this trade", @trade, class: "btn btn-danger m-1", method: :delete %>
    <% if session[:user_id] == @recipient.id %>
      <%= button_to "Confirm this trade", confirm_trade_path(@trade), class: "btn btn-success m-1" %>
    <% else %>
      <%= button_to "Send trade", user_path(@user), class: "btn btn-success m-1", method: :get %>
      <% flash[:notice] = "Trade successfully sent" %>
    <% end %>
  </div>
  <%= link_to "Edit this trade", edit_trade_path(@trade) %> |
  <%= link_to "Back to trades", trades_path %>
</div>